name: pytorch
channels:
  - pytorch
  - https://repo.anaconda.com/pkgs/free
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2019.5.15
  - certifi=2019.6.16
  - cffi=1.12.3
  - cpuonly=1.0
  - cycler=0.10.0
  - dbus=1.13.6
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.56.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2019.5
  - joblib=0.13.2
  - jpeg=9b
  - kiwisolver=1.1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - matplotlib=3.1.1
  - mkl=2019.5
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.0.2
  - ncurses=6.1
  - ninja=1.9.0
  - numpy=1.16.5
  - numpy-base=1.16.5
  - olefile=0.46
  - openssl=1.1.1d
  - pandas=0.25.1
  - patsy=0.5.1
  - pcre=8.43
  - pillow=6.1.0
  - pip=19.2.2
  - pycparser=2.19
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - python=3.7.4
  - python-dateutil=2.8.0
  - pytorch=1.2.0
  - pytz=2019.2
  - qt=5.9.7
  - readline=7.0
  - scikit-learn=0.21.2
  - scipy=1.3.1
  - seaborn=0.9.0
  - setuptools=41.0.1
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.29.0
  - statsmodels=0.10.1
  - tk=8.6.8
  - torchvision=0.4.0
  - tornado=6.0.3
  - wheel=0.33.4
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - bidict==0.18.2
prefix: /home/qlu/.conda/envs/pytorch

